# Fundamentos de pyTorch

En este archivo estarán contemplados los conceptos introducctorios al framework: sus estructuras básicas, propiedades y funciones junto a su marco teórico.

Gran parte del material fue sacado del bootcamp y esta en el siguiente sitio: https://www.learnpytorch.io/

<center><img src="img/bootcamp.png" alt="Bootcamp" width="500"></center>

In [1]:
# Importamos la libreria y visualizaremos su versión

import torch
print(torch.__version__)

2.7.1+cpu


In [2]:
# Otras librerias a utilizar

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Tensores

Los tensores son una estructura de datos muy eficiente para almacenar grandes volumenes de información dado que son estructuras N dimensionales de NxNxN dimensiones siendo N >=0.
Si bien esta definición no es para nada estrictamente matemática, como informáticos podrémos valernos de esta para entender con que estáremos trabajando. 

<center><img src="img/tensor.png" alt="Bootcamp" width="500"></center>

PyTorch trata a los tensores mediante vectores de numpy. 

Es imposible acordarse de memoria todos los tipos y propiedades de los tensores, es por esto que nunca esta demás tener presente la documentación oficial de pyTorch: https://docs.pytorch.org/docs/stable/tensors.html

In [3]:
# Tensor escalar junto a algunas funciones y propiedades

scalar = torch.tensor(7)

print(f"Tensor: {scalar}")
print(f"Dimensión: {scalar.ndim}")
print(f"Valor de un tensor de un solo elemento: {scalar.item}")


Tensor: 7
Dimensión: 0
Valor de un tensor de un solo elemento: <built-in method item of Tensor object at 0x000002498DDEB390>


In [4]:
# Tensor vector junto a algunas funciones y propiedades
# Recordar que los vectores en Python son en realidad listas

vector = torch.tensor([7,7])
vector

print(f"Vector: {vector}")
print(f"Tamaño del vector contenido: {vector.shape}") # Forma

Vector: tensor([7, 7])
Tamaño del vector contenido: torch.Size([2])


In [5]:
# Matrices

matriz = torch.tensor([[7,8],
                       [9, 10]])

print(f"Matriz: {matriz}")  
print(f"Dimensión de la matriz: {matriz.ndim}")
print(f"Forma u orden de la matriz: {matriz.shape}")

Matriz: tensor([[ 7,  8],
        [ 9, 10]])
Dimensión de la matriz: 2
Forma u orden de la matriz: torch.Size([2, 2])


In [6]:
# Tensores

tensor = torch.tensor([[[1, 2, 3],
                        [5, 4, 1],
                        [10, 0, -1]]])

print("Tensor:")
print(f"{tensor}")
print(f"Dimensión del tensor: {tensor.ndim}")
print(f"Tamaño u orden del tensor: {tensor.shape}")  

Tensor:
tensor([[[ 1,  2,  3],
         [ 5,  4,  1],
         [10,  0, -1]]])
Dimensión del tensor: 3
Tamaño u orden del tensor: torch.Size([1, 3, 3])


# Dimensión de los tensores

Para analizar el orden de los tensores en un código que es plano, en donde no podemos ver directamente los tensores como si fueran un "cubo rubik" debemos analizar la cantidad de elementos entre corchetes creados.
La función tensor.shape no falla, está en nosotros comprender el funcionamiento de esta y los tensores como estructuras lógicas que almacenan los datos en cuestión, sean del tipo que sean.

# Tensores con valores aleatorios

Las redes neuronales no tienen manera de saber que valores ingresarán en su capa de entrada, por lo que una forma de simular estas posibles estructuras es crear tensores con valores aleratorios comprendidos en un determinado dominio especificado en la función rand()

In [7]:
tensor_random = torch.rand(3, 4) # Orden del tensor
print("Tensor random: ")
print(f"{tensor_random}")
print(f"Dimensión del tensor: {tensor_random.ndim}")
print(f"Orden del tensor: {tensor_random.shape}")

Tensor random: 
tensor([[0.0065, 0.2001, 0.4700, 0.1892],
        [0.8559, 0.3059, 0.8484, 0.6446],
        [0.5072, 0.9482, 0.7944, 0.5032]])
Dimensión del tensor: 2
Orden del tensor: torch.Size([3, 4])


# Tensor análogo al de procesamiento de imagenes de datasets de Kaggle de números, caras, entre otros.

Estos tensores son de 224x224 y utilizan RGB (3 colores mezclados). 
Las fotos son infinitas, la combinación de colores también, y el tamaño el mismo dado que se trabaja con un set de datos especificamente preparado con fines educativos

In [8]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # alto, ancho, colores(R,G,B) --> Esto puede estar en diferente orden, es decir: primero los colores y después el alto y ancho, o al revés. 
print(f"Orden del tensor: {random_image_size_tensor.shape}")
print(f"Dimensión del tensor: {random_image_size_tensor.ndim}")

Orden del tensor: torch.Size([224, 224, 3])
Dimensión del tensor: 3


# Tensor de 0 o 1

Ideal para realizar filtros de tamaños asociados a tensores que pueden o no tener salidas validas según requerimientos.
El tipo de dato (dtype) es float32  

In [9]:
tensor_ceros = torch.zeros(size=(3,4))
tensor_ceros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
tensor_unos = torch.ones(size=(3, 4))
tensor_unos

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Tensores con determinado rango y tamaño

Con torch.arange() podrémos realizar tensores con tamaños, valores y saltos asociados

In [11]:
cero_a_nueve = torch.arange(10)
print(f"Tensor 0 a 9: {cero_a_nueve}")

uno_a_diez = torch.arange(start=1, end=11)
print(f"Tensor 1 a 10: {uno_a_diez}")

con_pasos = torch.arange(start=1, end=10, step=2)
print(f"De 1 a 10 de 2 en 2: {con_pasos}")

Tensor 0 a 9: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Tensor 1 a 10: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
De 1 a 10 de 2 en 2: tensor([1, 3, 5, 7, 9])


# Like: creará tensores iguales en estructura a otros pero con otros valores

In [12]:
diez_ceros = torch.zeros_like(input=uno_a_diez)
print(f"Tensor 0: {diez_ceros}")

Tensor 0: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


# Tipos de datos en tensores
Debemos tener en cuenta determinadas propiedades de los tensores tales como:
- Tipos de datos en tensores
- Tamaño de los tensores
- Propiedad DEVICE

In [13]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # TIPO DE DATO
                               device=None, # CPU
                               requires_grad=False) # NO TENGO IDEA
float_32_tensor.dtype

torch.float32

In [14]:
# Tensor de prueba para probar las propiedades mencionadas arriba

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6275, 0.8724, 0.4323, 0.9507],
        [0.1394, 0.3529, 0.4208, 0.0805],
        [0.3749, 0.9572, 0.0265, 0.4256]])

In [15]:
print(f"Tipo de data: {some_tensor.dtype}")
print(f"Orden del tensor: {some_tensor.shape}")
print(f"Se va a ejecutar en: {some_tensor.device}")

Tipo de data: torch.float32
Orden del tensor: torch.Size([3, 4])
Se va a ejecutar en: cpu


# Operaciones con tensores

Suma, resta, multiplicación, división

In [16]:
# Craré entonces un tensor para realizar operaciones, estos son mutables: si realizamos una operación con estos cambiarán su estructura. 

tensor_operaciones = torch.tensor([1, 2, 3])

print(f"Tensor original: {tensor_operaciones}")
print(f"Tensor + 10: {tensor_operaciones + 10}") # Sumará 10 a cada elemento del tensor en cuestión 
print(f"Tensor * 10: {tensor_operaciones * 10}") # Multplicará por 10 a cada elemento del tensor en cuestión
print(f"Tensor - 10: {tensor_operaciones - 10}") # Restará 10 a cada elemento del tensor en cuestión

Tensor original: tensor([1, 2, 3])
Tensor + 10: tensor([11, 12, 13])
Tensor * 10: tensor([10, 20, 30])
Tensor - 10: tensor([-9, -8, -7])


In [17]:
# Esto puede hacerse con funciones que pyTorch nos proporciona:

print(f"Tensor + 10: {torch.add(tensor_operaciones, 10)}")
print(f"Tensor * 10: {torch.mul(tensor_operaciones, 10)}")
print(f"Tensor - 10: {torch.sub(tensor_operaciones, 10)}")

Tensor + 10: tensor([11, 12, 13])
Tensor * 10: tensor([10, 20, 30])
Tensor - 10: tensor([-9, -8, -7])


# Operaciones con matrices

Las matices son pares ordenados que pueden ser sumados o multiplicados.
En caso de tener una resta se cambiará el signo de la matriz con el signo adelante y se sumaran.
Para que una matriz de orden *n.m* se pueda multiplicar por una *n.m* --> m = n

<center><img src="img/mul_matrices.png" alt="Bootcamp" width="500"></center>

Cada fila deberá ser multiplicada por cada columna según el índice de la nueva matriz obtenida de orden *m.m*

A su vez en ciertas ocasiones debemos usar la matiz transpuesta: esta invertirá las filas por columnas:

<center><img src="img/matriz_transpuesta.png" alt="m_transpuesta" width="500"></center>

In [18]:
# Para el primer ejemplo usaré un tensor de orden 1,3 (1 fila, 3 columnas)

tensor = torch.tensor([1,2,3]) # 1 * 1, 2 * 2, 3 * 3
print(f"Producto entre los elementos {tensor*tensor}")

# Esto sin embargo no es un producto de matrices: el orden de la matriz de retorno debería ser 1x1, para esto entonces usarémos torch.matmul(tensor, tensor)

print(f"Producto matricial: {torch.matmul(tensor, tensor)}")

Producto entre los elementos tensor([1, 4, 9])
Producto matricial: 14


In [19]:
# Ejemplo de multiplicación matricial de dos tensores:

tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

producto_matricial = torch.matmul(tensor_a, tensor_b)

producto_matricial


tensor([[19, 22],
        [43, 50]])

In [20]:
# Matriz transpuesta: tensor.T

tensor_a.T

tensor([[1, 3],
        [2, 4]])

# Funciones de agregación en tensores

Son similares a las de SQL: algunas de estas son min, max, mean, sum

In [21]:
# Crearé un tensor nuevo para probar estas y mostrar su funcionamiento

tensor_agregacion = torch.arange(0, 101, 10)
tensor_agregacion

print(f"Minimo: {torch.min(tensor_agregacion)}")
print(f"Maximo: {torch.max(tensor_agregacion)}")
print(f"Promedio: {torch.mean(tensor_agregacion.type(torch.float32))}") # Un lio el mean :)
print(f"Suma de los elementos: {torch.sum(tensor_agregacion)}")


Minimo: 0
Maximo: 100
Promedio: 50.0
Suma de los elementos: 550


In [22]:
# Con otras funciones de tipo estructura.funcion()

minimo = tensor_agregacion.min() # Hará uso de una función y deberá ser asignado a una varible para luego ser mostrado
maximo = tensor_agregacion.max()
promedio = tensor_agregacion.float().mean()
suma = tensor_agregacion.sum()

print(f"Minimo: {minimo}")
print(f"Maximo: {maximo}")
print(f"Promedio: {promedio}")
print(f"Suma: {suma}")

Minimo: 0
Maximo: 100
Promedio: 50.0
Suma: 550


# Encontrando índices de elementos específicos

Podemos mediante funciones proporcionadas por pyTorch encontrar valores minimos, maximos, entre otros (tal como se vio) y su índice o posición dentro de este.

In [23]:
tensor_max_min = torch.arange(start=0, end=101, step=10)
print(f"Elemento más chico: {tensor_max_min.argmin()}") # Minimo
print(f"Elemento más grande: {tensor_max_min.argmax()}") # Maximo

Elemento más chico: 0
Elemento más grande: 10


# reshape, stacking, squeezing, unsqueezing and permuting

*Reshaping* - cambia un tensor de entrada a una forma definida.

*View* - devuelve una vista de un tensor de entrada de cierta forma, pero mantiene la misma memoria que el tensor original.

*Stacking* - combina múltiples tensores uno encima de otro (vstack) o uno al lado del otro (hstack).

*Squeeze* - elimina todas las dimensiones de tamaño 1 de un tensor.

*Unsqueeze* - añade una dimensión de tamaño 1 a un tensor objetivo.

*Permute* - devuelve una vista de la entrada con las dimensiones permutadas (intercambiadas) de una manera específica.

In [24]:
# Tensor de prueba
tensor_prueba = torch.arange(1., 10.)
tensor_prueba

# Reshape: reordena el tensor
tensor_reshepe_nueve_uno = tensor_prueba.reshape(9, 1)
print(f"Tensor nueve a uno: {tensor_reshepe_nueve_uno}")

tensor_reshape_uno_nueve = tensor_prueba.reshape(1, 9)
print(f"Tensor {tensor_reshape_uno_nueve}")

Tensor nueve a uno: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Tensor tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [25]:
# View: cambia la vista del tensor según el orden indicado, pero no lo cambia como tal
print(f"Tensor cambiado desde el view: {tensor_prueba.view(1,9)}")

Tensor cambiado desde el view: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [26]:
# Stack
tensor_stack = torch.stack([tensor_prueba, tensor_prueba]) 
print(f"{tensor_stack}") # Apila el mismo tensor según dimensiones indicada con dim

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [27]:
# Squeezing: Quita una dimensión del tensor y ordena estos como si fueran de 1 o 0.

# Tensor con shape (1, 5, 1)
tensor = torch.tensor([[[1], [2], [3], [4], [5]]])
print(f"Tensor original: {tensor}")  # torch.Size([1, 5, 1])
print(f"")
# Aplicamos squeeze
tensor_squeezed = tensor.squeeze()
print(f"Shape tras squeeze: {tensor_squeezed.shape}")  # torch.Size([5])
print(tensor_squeezed)  # tensor([1, 2, 3, 4, 5])

Tensor original: tensor([[[1],
         [2],
         [3],
         [4],
         [5]]])

Shape tras squeeze: torch.Size([5])
tensor([1, 2, 3, 4, 5])


In [28]:
# Unsqueezing: agrega una dimensión al tensor en donde lo indiquemos

tensor_unsqueezing = torch.tensor([1, 2, 4])
print(f"Tensor original: {tensor_unsqueezing}")

tensor_unsqueezing_cero = tensor_unsqueezing.unsqueeze(0)
print(f"Tensor unsqueeezing cero: {tensor_unsqueezing_cero}")

tensor_unsqueezing_uno = tensor_unsqueezing.unsqueeze(1)
print(f"Tensor unsqueezing uno: {tensor_reshepe_nueve_uno}")

Tensor original: tensor([1, 2, 4])
Tensor unsqueeezing cero: tensor([[1, 2, 4]])
Tensor unsqueezing uno: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [29]:
# Permuting tensors: cambia el orden de las dimensiones de un tensor sin modificar los datos sino la forma en la que se lee
# Analogo a la matriz transpuesta

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])  # shape: (2, 3)
print("Original:\n", x)
print("Forma:", x.shape)  # (2, 3)

# Usamos permute para invertir las dimensiones
x_permutado = x.permute(1, 0)  # nueva forma: (3, 2)
print("\nPermutado:\n", x_permutado)
print("Nueva forma:", x_permutado.shape)  # (3, 2)

Original:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Forma: torch.Size([2, 3])

Permutado:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])
Nueva forma: torch.Size([3, 2])


In [30]:
# Ejemplo con una foto 225x255x3
tensor_imagen = torch.rand(size=(255,255,3))

print(f"Tensor imagen: {tensor_imagen}")

tensor_imagen_permutado = tensor_imagen.permute(2, 0, 1)

print(f"Tensor permutado: {tensor_imagen_permutado}")

Tensor imagen: tensor([[[5.3412e-01, 7.8636e-01, 7.1820e-01],
         [4.8367e-01, 5.0565e-01, 1.0550e-01],
         [8.2807e-02, 4.4185e-01, 3.6433e-01],
         ...,
         [2.7581e-01, 9.2777e-01, 4.5533e-01],
         [7.8643e-01, 3.4519e-01, 1.5912e-01],
         [5.2066e-01, 8.4317e-01, 2.8614e-01]],

        [[9.4766e-01, 7.8940e-01, 4.3339e-01],
         [1.7717e-01, 8.9380e-01, 5.0248e-01],
         [2.3280e-02, 7.5168e-01, 7.0389e-01],
         ...,
         [4.8822e-01, 2.0989e-01, 5.2245e-01],
         [3.2859e-01, 6.8142e-01, 6.4889e-01],
         [8.7267e-01, 4.4669e-01, 7.7078e-01]],

        [[3.0317e-01, 9.2919e-01, 7.6589e-01],
         [5.3940e-01, 3.6331e-01, 2.8141e-01],
         [7.3621e-01, 9.3254e-01, 6.6202e-01],
         ...,
         [5.5458e-01, 4.0727e-01, 5.8102e-01],
         [1.9459e-01, 5.0436e-01, 7.0351e-01],
         [4.2931e-01, 6.2231e-01, 9.7744e-01]],

        ...,

        [[4.2359e-01, 3.2365e-01, 4.3393e-01],
         [7.2216e-01, 5.7534e-

# Índices con PyTorch

Para seleccionar datos de un índice específico debemos trabajar igual que con vectores de numpy
Al sumarse más dimensiones deja de ser mecánico y fácil, requiere mucha práctica e inclusive abstracción

In [31]:
tensor_indices = torch.arange(1, 10).reshape(1, 3, 3)
print(f"Tesnor indices: {tensor_indices}")

print(f"Primera dimensión --> tensor_indices[0]:")
print(f"{tensor_indices[0]}")
print(f"Segunda dimensión, primer 'fila' de elementos --> tensor_indices[0][0]:")
print(f"{tensor_indices[0][0]}")

print(f"Segunda dimensión, segunda 'fila' de elementos --> tensor_indices[0][1]:")
print(f"{tensor_indices[0][1]}")

print(f"Segunda dimensión, tercera 'fila' de elementos --> tensor_indices[0][2]:")
print(f"{tensor_indices[0][2]}")

print(f"Elementos específicos -->tensor_indices[dimension][fila][posición]")
print(f"Elemento centra --> tensor_indices[0][1][1]:")
print(f"{tensor_indices[0][1][1]}")

Tesnor indices: tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Primera dimensión --> tensor_indices[0]:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Segunda dimensión, primer 'fila' de elementos --> tensor_indices[0][0]:
tensor([1, 2, 3])
Segunda dimensión, segunda 'fila' de elementos --> tensor_indices[0][1]:
tensor([4, 5, 6])
Segunda dimensión, tercera 'fila' de elementos --> tensor_indices[0][2]:
tensor([7, 8, 9])
Elementos específicos -->tensor_indices[dimension][fila][posición]
Elemento centra --> tensor_indices[0][1][1]:
5


In [32]:
# Podrémos también acceder a todos los elementos hasta determinado elemento con slice 

print(tensor_indices[:,])
print(tensor_indices[:,1,2]) # Y así, hacer muchos para practicar

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([6])


# PyTorch y numPy

In [33]:
np_array =  np.arange(1.0, 8.0)

print(np_array.dtype)


tensor = torch.from_numpy(np_array)
tensor

float64


tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [34]:
# Sumar uno a cada eleento con tensores de numpy

np_tensor = np.arange(1.0, 11.0)
np_tensor = np_tensor + 1 # con dtype=tipo podrémos cambiar el tipo de vector de np

np_tensor

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
# Aleatoriedad

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor_aleatorio_a = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
tensor_aleatorio_b = torch.rand(3, 4)

print(f"tensor_aleatorio_a: ")
print(f"{tensor_aleatorio_a}")
print(f"tensor_aleatorio_b: ")
print(f"{tensor_aleatorio_b}")

print(tensor_aleatorio_a == tensor_aleatorio_b )

tensor_aleatorio_a: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor_aleatorio_b: 
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
